apiVersion: apps/v1
kind: Deployment
metadata:
  name: tictactoe
  namespace: tictactoe
  labels:
    app: tictactoe
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tictactoe
  template:
    metadata:
      labels:
        app: tictactoe
    spec:
      containers:
        - name: tictactoe
          # CI will replace ghcr.io/thuanthentran/nt113_tictactoe_gitops:bf26bc19d69d09c6448bb47ec8e89bd68b5f542f with the built image (ghcr.io/owner/repo:sha)
          image: ghcr.io/thuanthentran/nt113_tictactoe_gitops:bf26bc19d69d09c6448bb47ec8e89bd68b5f542f
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      imagePullSecrets:
        - name: ghcr-secret
