apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tictactoe-hpa
  namespace: tictactoe
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tictactoe
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
