apiVersion: v1
kind: Namespace
metadata:
  name: network-testing
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf3-server
  namespace: network-testing
  labels:
    app: iperf3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf3
  template:
    metadata:
      labels:
        app: iperf3
    spec:
      containers:
      - name: iperf3
        image: networkstatic/iperf3
        args: ['-s']
        ports:
        - containerPort: 5201
          name: iperf3-port
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: iperf3-service
  namespace: network-testing
spec:
  type: NodePort
  selector:
    app: iperf3
  ports:
  - port: 5201
    targetPort: 5201
    nodePort: 30201 # Bạn có thể đổi cổng này nếu cần
    protocol: TCP